// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication_EF_Core_Code_First.Models;

namespace WebApplication_EF_Core_Code_First.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20200416160920_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication_EF_Core_Code_First.Models.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama");

                    b.Property<string>("BolumAdi");

                    b.Property<int>("UniversiteId");

                    b.HasKey("BolumId");

                    b.HasIndex("UniversiteId");

                    b.ToTable("Bolumler");
                });

            modelBuilder.Entity("WebApplication_EF_Core_Code_First.Models.Universite", b =>
                {
                    b.Property<int>("UniversiteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniversiteAdi");

                    b.HasKey("UniversiteId");

                    b.ToTable("Universiteler");
                });

            modelBuilder.Entity("WebApplication_EF_Core_Code_First.Models.Bolum", b =>
                {
                    b.HasOne("WebApplication_EF_Core_Code_First.Models.Universite", "Universite")
                        .WithMany("Bolumler")
                        .HasForeignKey("UniversiteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
